version: '3'
services:
    app-dev:
        profiles:
            - dev
        container_name: finance-be-dev
        build:
            dockerfile: Dockerfile
            context: .
            target: build-phase-1
        restart: always
        ports:
            - ${PORT}:3000
            # debugging
            - 9229:9229
        depends_on:
            - db-dev
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
        volumes:
            - ./src/:/app/src
            - ./node_modules/:/app/node_modules
        command: npm run start:debug

    app-prod:
        profiles:
            - prod
        container_name: finance-be-prod
        image: shushman/finance-be:latest
        restart: always
        ports:
            - ${PORT}:3000
        depends_on:
            - db-prod
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}

    db-dev:
        profiles:
            - dev
        container_name: finance-db-dev
        image: postgres:15
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./dbdata:/var/lib/postgresql/data

    db-prod:
        profiles:
            - prod
        container_name: finance-db-prod
        image: postgres:15-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
