version: '3'
services:
  app:
    container_name: finance-be
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
      # debugging
      - 9229:9229
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${PORT}
    volumes:
      - ./src/:/app/src
      - ./node_modules/:/app/node_modules
  db:
    container_name: finance-db
    image: postgres
    restart: always
    ports:
     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./dbdata:/var/lib/postgresql/data