version: '3'
services:
    app-dev:
        profiles:
            - dev
        container_name: todo-be-dev
        build:
            dockerfile: Dockerfile
            context: .
            target: build-phase-1
        restart: always
        ports:
            - 127.0.0.1:${PORT}:3000
            # debugging
            - 127.0.0.1:9229:9229
        depends_on:
            - db-dev
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
            - SALT_ROUNDS=${SALT_ROUNDS}
            - JWT_SECRET=${JWT_SECRET}

        volumes:
            - ./src/:/app/src

        command: npm run start:debug

    app-prod:
        profiles:
            - prod
        container_name: todo-be-prod
        image: shushman/todo-be:latest
        restart: always
        ports:
            - 127.0.0.1:${PORT}:3000
        depends_on:
            - db-prod
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
            - SALT_ROUNDS=${SALT_ROUNDS}
            - JWT_SECRET=${JWT_SECRET}

    db-dev:
        profiles:
            - dev
        container_name: todo-db-dev
        image: postgres:15
        restart: always
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./dbdata:/var/lib/postgresql/data

    db-prod:
        profiles:
            - prod
        container_name: todo-db-prod
        image: postgres:15-alpine
        restart: always
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
