name: Deploy to Docker hub

on:
  workflow_run:
    workflows: ['Code quality gates']
    types:
      - completed
    branches: ['main']

jobs:
  success:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build . -t ${{secrets.DOCKER_USERNAME}}/finance-be:latest
      - run: docker push ${{secrets.DOCKER_USERNAME}}/finance-be:latest

  failure:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - run: echo 'The triggering workflow failed'
