name: Deploy to VPS

on:
  workflow_run:
    workflows: ['Publish to Docker hub']
    types:
      - completed
    branches: ['main']

jobs:
  success:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@v3

      - name: Copy docker-compose.yml via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USER}}
          key: ${{secrets.VPS_KEY}}
          source: './docker-compose.yml'
          target: '~/finance/be'
          overwrite: true

      - name: Get all the most recent images and start/restart the app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USER}}
          key: ${{secrets.VPS_KEY}}
          script: |
            cd ~/finance/be
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker compose --profile prod down --rmi all
            docker compose --env-file ./.env up

  failure:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1
