name: Publish to Docker hub

on:
  workflow_run:
    workflows: ['Set maintenance page after passed quality gates']
    types:
      - completed
    branches: ['main']

jobs:
  success_publish_dockerhub:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build . -t ${{secrets.DOCKER_USERNAME}}/todo-be:latest
      - run: docker push ${{secrets.DOCKER_USERNAME}}/todo-be:latest

  failure_publish_dockerhub:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1
